
running 1 test
test verifier::tests::test_eval_l_1_and_l_last ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 1 test
test test_fib ... FAILED

failures:

---- test_fib stdout ----
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
[dummy access] 60
[dummy access] 61
[dummy access] 62
[dummy padding] 62
Error: Mismatch between evaluation and opening of quotient polynomial

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/backtrace.rs:328:13
   3: std::backtrace::Backtrace::capture
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/backtrace.rs:296:9
   4: anyhow::error::<impl anyhow::Error>::msg
             at /Users/sebastienladuca/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.52/src/error.rs:79:36
   5: anyhow::private::format_err
             at /Users/sebastienladuca/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.52/src/lib.rs:660:13
   6: maru_stark::verifier::verify_stark_proof_with_challenges
             at ./src/verifier.rs:155:9
   7: maru_stark::verifier::verify_stark_proof
             at ./src/verifier.rs:52:5
   8: fib::test_fib
             at ./tests/fib.rs:241:5
   9: fib::test_fib::{{closure}}
             at ./tests/fib.rs:199:1
  10: core::ops::function::FnOnce::call_once
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/core/src/ops/function.rs:248:5
  11: core::ops::function::FnOnce::call_once
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/core/src/ops/function.rs:248:5
  12: test::__rust_begin_short_backtrace
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/test/src/lib.rs:572:5
  13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/alloc/src/boxed.rs:1951:9
  14: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/core/src/panic/unwind_safe.rs:271:9
  15: std::panicking::try::do_call
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/panicking.rs:492:40
  16: std::panicking::try
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/panicking.rs:456:19
  17: std::panic::catch_unwind
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/panic.rs:137:14
  18: test::run_test_in_process
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/test/src/lib.rs:595:18
  19: test::run_test::run_test_inner::{{closure}}
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/test/src/lib.rs:489:39
  20: test::run_test::run_test_inner::{{closure}}
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/test/src/lib.rs:516:37
  21: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/sys_common/backtrace.rs:122:18
  22: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/thread/mod.rs:501:17
  23: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/core/src/panic/unwind_safe.rs:271:9
  24: std::panicking::try::do_call
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/panicking.rs:492:40
  25: std::panicking::try
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/panicking.rs:456:19
  26: std::panic::catch_unwind
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/panic.rs:137:14
  27: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/thread/mod.rs:500:30
  28: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/core/src/ops/function.rs:248:5
  29: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/alloc/src/boxed.rs:1951:9
  30: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/alloc/src/boxed.rs:1951:9
  31: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/sys/unix/thread.rs:108:17
  32: __pthread_start
thread 'test_fib' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/test/src/lib.rs:184:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/core/src/panicking.rs:218:23
   3: core::panicking::assert_failed
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/core/src/panicking.rs:181:5
   4: test::assert_test_result
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/test/src/lib.rs:184:5
   5: fib::test_fib::{{closure}}
             at ./tests/fib.rs:199:1
   6: core::ops::function::FnOnce::call_once
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/core/src/ops/function.rs:248:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    test_fib

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.07s

